version: 2

project_name: lockenv

before:
  hooks:
    - go mod tidy
    - go build -o lockenv .
    - mkdir -p completions
    - ./lockenv completion bash > completions/lockenv.bash
    - ./lockenv completion zsh > completions/_lockenv
    - ./lockenv completion fish > completions/lockenv.fish

builds:
  - binary: lockenv
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - formats: [tar.gz]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - completions/*

nfpms:
  - package_name: lockenv
    vendor: Illarion Kovalchuk
    homepage: https://github.com/illarion/lockenv
    maintainer: Illarion Kovalchuk
    description: Simple, CLI-friendly secret storage
    license: MIT
    formats:
      - deb
      - rpm
    contents:
      - src: completions/lockenv.bash
        dst: /usr/share/bash-completion/completions/lockenv
      - src: completions/_lockenv
        dst: /usr/share/zsh/vendor-completions/_lockenv
      - src: completions/lockenv.fish
        dst: /usr/share/fish/vendor_completions.d/lockenv.fish

homebrew_casks:
  - repository:
      owner: illarion
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    homepage: https://github.com/illarion/lockenv
    description: Simple, CLI-friendly secret storage
    license: MIT
    completions:
      bash: completions/lockenv.bash
      zsh: completions/_lockenv
      fish: completions/lockenv.fish

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
